version: '3'
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    expose:
      - 3306
    env_file:
    - stack.env
    volumes:
      - raptor-db:/var/lib/mysql/

  raptorapp:
    image: zediious/raptor-web:latest
    container_name: raptorapp
    expose:
      - 80
    env_file:
    - stack.env
    volumes:
      - raptor-media:/raptorWebApp/raptorWeb/media
      - raptor-conf:/raptorWebApp/docker/nginx/conf.d/
      - ./stack.env:/raptorWebApp/stack.env
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - raptor-media:/raptor_app/media
      - raptor-conf:/etc/nginx/conf.d/
    depends_on:
      - raptorapp

volumes:
  raptor-db:
  raptor-conf:
  raptor-media:
