version: '3'

services:
  raptorapp:
    image: raptorweb:latest
    command: sh -c "cd raptorWeb &&
                    conda run -n djangoWork python manage.py makemigrations &&
                    conda run -n djangoWork python manage.py migrate &&
                    conda run -n djangoWork python manage.py collectstatic --noinput &&
                    conda run -n djangoWork gunicorn raptorWeb.wsgi:application --bind 0.0.0.0:80"
    container_name: raptorapp
    # env_file:
    #   - ./config/variables.env
    expose:
      - 80
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - raptorapp
